apiVersion: kubeone.io/v1beta1
kind: KubeOneCluster
versions:
  kubernetes: '1.21.5'

cloudProvider:
  hetzner: {}
  external: true

addons:
  enable: true
  path: "./addons"
  addons:
  - name: unattended-upgrades
