apiVersion: kubeone.io/v1beta1
kind: KubeOneCluster
versions:
  kubernetes: '1.21.4'
cloudProvider:
  hetzner: {}
  external: true
addons:
  enable: false
  path: "./addons"
  addons:
  - name: unattended-upgrades
